import { InstitutionConfig, Teacher, Subject, Room, ClassDivision, ScheduleEntry } from './types';

export const initialInstitutionConfig: InstitutionConfig = {
  collegeName: 'Tech University of Advanced Sciences',
  academicYear: '2026-2027',
  semester: 'Odd Semester (Jul - Dec)',
  department: 'Computer Science & Engineering',
  course: 'B.Tech / B.E. in CSE & AI',
  workingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  timings: {
    startTime: '09:00',
    endTime: '16:10',
    periodsPerDay: 6,
    periodDurationMinutes: 55,
    lunchAfterPeriod: 3,
    lunchDurationMinutes: 50,
  },
};

export const initialTeachers: Teacher[] = [
  {
    id: 't-1',
    name: 'Dr. Arvind Sharma',
    teacherId: 'CSE-101',
    preferredTime: 'Morning',
    maxHoursPerDay: 4,
    maxHoursPerWeek: 16,
    unavailableDays: ['Saturday'],
    unavailableSlots: ['Monday-P1', 'Wednesday-P6'],
    department: 'Artificial Intelligence',
  },
  {
    id: 't-2',
    name: 'Prof. Neha Verma',
    teacherId: 'CSE-102',
    preferredTime: 'Any',
    maxHoursPerDay: 4,
    maxHoursPerWeek: 18,
    unavailableDays: [],
    unavailableSlots: ['Friday-P5', 'Friday-P6'],
    department: 'Software Engineering',
  },
  {
    id: 't-3',
    name: 'Dr. Rajesh Gupta',
    teacherId: 'CSE-103',
    preferredTime: 'Afternoon',
    maxHoursPerDay: 4,
    maxHoursPerWeek: 15,
    unavailableDays: [],
    unavailableSlots: ['Tuesday-P1', 'Tuesday-P2'],
    department: 'Database Systems',
  },
  {
    id: 't-4',
    name: 'Prof. Ananya Iyer',
    teacherId: 'CSE-104',
    preferredTime: 'Morning',
    maxHoursPerDay: 4,
    maxHoursPerWeek: 18,
    unavailableDays: [],
    unavailableSlots: [],
    department: 'Computer Networks',
  },
  {
    id: 't-5',
    name: 'Dr. Vikram Rathore',
    teacherId: 'CSE-105',
    preferredTime: 'Any',
    maxHoursPerDay: 5,
    maxHoursPerWeek: 20,
    unavailableDays: ['Saturday'],
    unavailableSlots: ['Thursday-P1'],
    department: 'Operating Systems',
  },
  {
    id: 't-6',
    name: 'Prof. Meera Sen',
    teacherId: 'CSE-106',
    preferredTime: 'Afternoon',
    maxHoursPerDay: 4,
    maxHoursPerWeek: 16,
    unavailableDays: [],
    unavailableSlots: ['Monday-P5', 'Monday-P6'],
    department: 'Theory of Computation',
  },
  {
    id: 't-7',
    name: 'Dr. Sanjay Kapoor',
    teacherId: 'CSE-107',
    preferredTime: 'Morning',
    maxHoursPerDay: 4,
    maxHoursPerWeek: 14,
    unavailableDays: ['Friday'],
    unavailableSlots: [],
    department: 'Cyber Security',
  },
  {
    id: 't-8',
    name: 'Prof. Kavita Nair',
    teacherId: 'CSE-108',
    preferredTime: 'Any',
    maxHoursPerDay: 4,
    maxHoursPerWeek: 16,
    unavailableDays: [],
    unavailableSlots: ['Wednesday-P1'],
    department: 'Cloud Computing',
  },
];

export const initialSubjects: Subject[] = [
  {
    id: 's-1',
    name: 'Advanced Machine Learning',
    code: 'CS-501',
    weeklyHours: 4,
    type: 'Theory',
    priority: 'Core',
    assignedTeacherId: 't-1',
    requiresLab: false,
    requiredEquipment: [],
    color: '#6366f1', // Indigo
  },
  {
    id: 's-2',
    name: 'AI & Deep Learning Lab',
    code: 'CS-501L',
    weeklyHours: 4,
    type: 'Practical',
    priority: 'Labs',
    assignedTeacherId: 't-1',
    requiresLab: true,
    requiredEquipment: ['GPU Cluster', 'AI Workstations'],
    color: '#8b5cf6', // Violet
  },
  {
    id: 's-3',
    name: 'Data Structures & Algorithms',
    code: 'CS-301',
    weeklyHours: 4,
    type: 'Theory',
    priority: 'Core',
    assignedTeacherId: 't-2',
    requiresLab: false,
    requiredEquipment: [],
    color: '#3b82f6', // Blue
  },
  {
    id: 's-4',
    name: 'DSA Programming Lab',
    code: 'CS-301L',
    weeklyHours: 4,
    type: 'Practical',
    priority: 'Labs',
    assignedTeacherId: 't-2',
    requiresLab: true,
    requiredEquipment: ['Linux Systems'],
    color: '#0ea5e9', // Sky
  },
  {
    id: 's-5',
    name: 'Database Management Systems',
    code: 'CS-402',
    weeklyHours: 3,
    type: 'Theory',
    priority: 'Core',
    assignedTeacherId: 't-3',
    requiresLab: false,
    requiredEquipment: [],
    color: '#10b981', // Emerald
  },
  {
    id: 's-6',
    name: 'DBMS & SQL Lab',
    code: 'CS-402L',
    weeklyHours: 2,
    type: 'Practical',
    priority: 'Labs',
    assignedTeacherId: 't-3',
    requiresLab: true,
    requiredEquipment: ['PostgreSQL Server'],
    color: '#059669', // Teal
  },
  {
    id: 's-7',
    name: 'Computer Networks & Security',
    code: 'CS-503',
    weeklyHours: 3,
    type: 'Theory',
    priority: 'Core',
    assignedTeacherId: 't-4',
    requiresLab: false,
    requiredEquipment: [],
    color: '#f59e0b', // Amber
  },
  {
    id: 's-8',
    name: 'Network Simulation Lab',
    code: 'CS-503L',
    weeklyHours: 2,
    type: 'Practical',
    priority: 'Labs',
    assignedTeacherId: 't-4',
    requiresLab: true,
    requiredEquipment: ['Cisco Routers', 'Wireshark Workstations'],
    color: '#d97706', // Amber dark
  },
  {
    id: 's-9',
    name: 'Operating Systems & Kernel',
    code: 'CS-401',
    weeklyHours: 4,
    type: 'Theory',
    priority: 'Core',
    assignedTeacherId: 't-5',
    requiresLab: false,
    requiredEquipment: [],
    color: '#ec4899', // Pink
  },
  {
    id: 's-10',
    name: 'Theory of Computation',
    code: 'CS-403',
    weeklyHours: 3,
    type: 'Theory',
    priority: 'Core',
    assignedTeacherId: 't-6',
    requiresLab: false,
    requiredEquipment: [],
    color: '#a855f7', // Purple
  },
  {
    id: 's-11',
    name: 'Cyber Security & Cryptography',
    code: 'CS-601',
    weeklyHours: 3,
    type: 'Theory',
    priority: 'Electives',
    assignedTeacherId: 't-7',
    requiresLab: false,
    requiredEquipment: [],
    color: '#ef4444', // Red
  },
  {
    id: 's-12',
    name: 'Cloud Computing & DevOps',
    code: 'CS-602',
    weeklyHours: 3,
    type: 'Theory',
    priority: 'Electives',
    assignedTeacherId: 't-8',
    requiresLab: false,
    requiredEquipment: [],
    color: '#14b8a6', // Cyan/Teal
  },
  {
    id: 's-13',
    name: 'Technical Communication & Library',
    code: 'HS-201',
    weeklyHours: 2,
    type: 'Theory',
    priority: 'Library',
    assignedTeacherId: 't-6',
    requiresLab: false,
    requiredEquipment: [],
    color: '#64748b', // Slate
  },
];

export const initialRooms: Room[] = [
  {
    id: 'r-101',
    roomNumber: 'LH-101 (Turing Lecture Hall)',
    capacity: 70,
    type: 'Classroom',
    availableEquipment: ['Smart Board', 'Projector', 'Audio System'],
  },
  {
    id: 'r-102',
    roomNumber: 'LH-102 (Von Neumann Hall)',
    capacity: 65,
    type: 'Classroom',
    availableEquipment: ['Smart Board', 'Projector'],
  },
  {
    id: 'r-103',
    roomNumber: 'LH-103 (Ramanujan Hall)',
    capacity: 60,
    type: 'Classroom',
    availableEquipment: ['Projector'],
  },
  {
    id: 'lab-201',
    roomNumber: 'AI & High Performance Computing Lab (L-201)',
    capacity: 45,
    type: 'Laboratory',
    availableEquipment: ['GPU Cluster', 'AI Workstations', 'Linux Systems'],
  },
  {
    id: 'lab-202',
    roomNumber: 'Systems & Networking Lab (L-202)',
    capacity: 50,
    type: 'Laboratory',
    availableEquipment: ['Linux Systems', 'PostgreSQL Server', 'Cisco Routers', 'Wireshark Workstations'],
  },
];

export const initialDivisions: ClassDivision[] = [
  {
    id: 'div-3a',
    name: 'Sem 3 - Div A (Core CSE)',
    semester: 3,
    strength: 58,
    defaultRoomId: 'r-101',
  },
  {
    id: 'div-5a',
    name: 'Sem 5 - Div A (AI Specialization)',
    semester: 5,
    strength: 62,
    defaultRoomId: 'r-102',
  },
  {
    id: 'div-7a',
    name: 'Sem 7 - Div A (Systems & Cloud)',
    semester: 7,
    strength: 55,
    defaultRoomId: 'r-103',
  },
];

// Pre-generated optimized initial schedule so user has immediate rich interactive data
export const initialScheduleEntries: ScheduleEntry[] = [
  // Sem 5 - Div A (AI Specialization)
  { id: 'se-101', subjectId: 's-1', teacherId: 't-1', roomId: 'r-102', divisionId: 'div-5a', day: 'Monday', period: 1, span: 1, isLocked: false },
  { id: 'se-102', subjectId: 's-7', teacherId: 't-4', roomId: 'r-102', divisionId: 'div-5a', day: 'Monday', period: 2, span: 1, isLocked: false },
  { id: 'se-103', subjectId: 's-2', teacherId: 't-1', roomId: 'lab-201', divisionId: 'div-5a', day: 'Monday', period: 4, span: 2, isLocked: true, notes: 'GPU Cluster reserved' },
  { id: 'se-104', subjectId: 's-12', teacherId: 't-8', roomId: 'r-102', divisionId: 'div-5a', day: 'Monday', period: 6, span: 1, isLocked: false },
  
  { id: 'se-105', subjectId: 's-1', teacherId: 't-1', roomId: 'r-102', divisionId: 'div-5a', day: 'Tuesday', period: 2, span: 1, isLocked: false },
  { id: 'se-106', subjectId: 's-7', teacherId: 't-4', roomId: 'r-102', divisionId: 'div-5a', day: 'Tuesday', period: 3, span: 1, isLocked: false },
  { id: 'se-107', subjectId: 's-8', teacherId: 't-4', roomId: 'lab-202', divisionId: 'div-5a', day: 'Tuesday', period: 4, span: 2, isLocked: false },

  { id: 'se-108', subjectId: 's-1', teacherId: 't-1', roomId: 'r-102', divisionId: 'div-5a', day: 'Wednesday', period: 1, span: 1, isLocked: false },
  { id: 'se-109', subjectId: 's-12', teacherId: 't-8', roomId: 'r-102', divisionId: 'div-5a', day: 'Wednesday', period: 2, span: 1, isLocked: false },
  { id: 'se-110', subjectId: 's-7', teacherId: 't-4', roomId: 'r-102', divisionId: 'div-5a', day: 'Wednesday', period: 3, span: 1, isLocked: false },
  { id: 'se-111', subjectId: 's-2', teacherId: 't-1', roomId: 'lab-201', divisionId: 'div-5a', day: 'Wednesday', period: 4, span: 2, isLocked: false },

  { id: 'se-112', subjectId: 's-1', teacherId: 't-1', roomId: 'r-102', divisionId: 'div-5a', day: 'Thursday', period: 2, span: 1, isLocked: false },
  { id: 'se-113', subjectId: 's-12', teacherId: 't-8', roomId: 'r-102', divisionId: 'div-5a', day: 'Thursday', period: 3, span: 1, isLocked: false },
  { id: 'se-114', subjectId: 's-13', teacherId: 't-6', roomId: 'r-102', divisionId: 'div-5a', day: 'Thursday', period: 4, span: 1, isLocked: false },
  { id: 'se-115', subjectId: 's-13', teacherId: 't-6', roomId: 'r-102', divisionId: 'div-5a', day: 'Thursday', period: 5, span: 1, isLocked: false },

  { id: 'se-116', subjectId: 's-11', teacherId: 't-7', roomId: 'r-102', divisionId: 'div-5a', day: 'Friday', period: 1, span: 1, isLocked: false },
  { id: 'se-117', subjectId: 's-11', teacherId: 't-7', roomId: 'r-102', divisionId: 'div-5a', day: 'Friday', period: 2, span: 1, isLocked: false },
  { id: 'se-118', subjectId: 's-11', teacherId: 't-7', roomId: 'r-102', divisionId: 'div-5a', day: 'Friday', period: 3, span: 1, isLocked: false },

  // Sem 3 - Div A (Core CSE)
  { id: 'se-201', subjectId: 's-3', teacherId: 't-2', roomId: 'r-101', divisionId: 'div-3a', day: 'Monday', period: 1, span: 1, isLocked: false },
  { id: 'se-202', subjectId: 's-5', teacherId: 't-3', roomId: 'r-101', divisionId: 'div-3a', day: 'Monday', period: 2, span: 1, isLocked: false },
  { id: 'se-203', subjectId: 's-9', teacherId: 't-5', roomId: 'r-101', divisionId: 'div-3a', day: 'Monday', period: 3, span: 1, isLocked: false },
  { id: 'se-204', subjectId: 's-4', teacherId: 't-2', roomId: 'lab-202', divisionId: 'div-3a', day: 'Monday', period: 4, span: 2, isLocked: false },

  { id: 'se-205', subjectId: 's-3', teacherId: 't-2', roomId: 'r-101', divisionId: 'div-3a', day: 'Tuesday', period: 1, span: 1, isLocked: false },
  { id: 'se-206', subjectId: 's-10', teacherId: 't-6', roomId: 'r-101', divisionId: 'div-3a', day: 'Tuesday', period: 2, span: 1, isLocked: false },
  { id: 'se-207', subjectId: 's-5', teacherId: 't-3', roomId: 'r-101', divisionId: 'div-3a', day: 'Tuesday', period: 3, span: 1, isLocked: false },
  { id: 'se-208', subjectId: 's-6', teacherId: 't-3', roomId: 'lab-202', divisionId: 'div-3a', day: 'Tuesday', period: 4, span: 2, isLocked: true },

  { id: 'se-209', subjectId: 's-9', teacherId: 't-5', roomId: 'r-101', divisionId: 'div-3a', day: 'Wednesday', period: 1, span: 1, isLocked: false },
  { id: 'se-210', subjectId: 's-3', teacherId: 't-2', roomId: 'r-101', divisionId: 'div-3a', day: 'Wednesday', period: 2, span: 1, isLocked: false },
  { id: 'se-211', subjectId: 's-10', teacherId: 't-6', roomId: 'r-101', divisionId: 'div-3a', day: 'Wednesday', period: 3, span: 1, isLocked: false },
  { id: 'se-212', subjectId: 's-4', teacherId: 't-2', roomId: 'lab-202', divisionId: 'div-3a', day: 'Wednesday', period: 4, span: 2, isLocked: false },

  { id: 'se-213', subjectId: 's-3', teacherId: 't-2', roomId: 'r-101', divisionId: 'div-3a', day: 'Thursday', period: 1, span: 1, isLocked: false },
  { id: 'se-214', subjectId: 's-9', teacherId: 't-5', roomId: 'r-101', divisionId: 'div-3a', day: 'Thursday', period: 2, span: 1, isLocked: false },
  { id: 'se-215', subjectId: 's-5', teacherId: 't-3', roomId: 'r-101', divisionId: 'div-3a', day: 'Thursday', period: 3, span: 1, isLocked: false },
  { id: 'se-216', subjectId: 's-10', teacherId: 't-6', roomId: 'r-101', divisionId: 'div-3a', day: 'Thursday', period: 4, span: 1, isLocked: false },

  { id: 'se-217', subjectId: 's-9', teacherId: 't-5', roomId: 'r-101', divisionId: 'div-3a', day: 'Friday', period: 1, span: 1, isLocked: false },
  { id: 'se-218', subjectId: 's-13', teacherId: 't-6', roomId: 'r-101', divisionId: 'div-3a', day: 'Friday', period: 2, span: 1, isLocked: false },

  // Sem 7 - Div A (Systems & Cloud)
  { id: 'se-301', subjectId: 's-12', teacherId: 't-8', roomId: 'r-103', divisionId: 'div-7a', day: 'Monday', period: 1, span: 1, isLocked: false },
  { id: 'se-302', subjectId: 's-11', teacherId: 't-7', roomId: 'r-103', divisionId: 'div-7a', day: 'Monday', period: 3, span: 1, isLocked: false },
  { id: 'se-303', subjectId: 's-12', teacherId: 't-8', roomId: 'r-103', divisionId: 'div-7a', day: 'Tuesday', period: 1, span: 1, isLocked: false },
  { id: 'se-304', subjectId: 's-11', teacherId: 't-7', roomId: 'r-103', divisionId: 'div-7a', day: 'Tuesday', period: 2, span: 1, isLocked: false },
  { id: 'se-305', subjectId: 's-12', teacherId: 't-8', roomId: 'r-103', divisionId: 'div-7a', day: 'Wednesday', period: 3, span: 1, isLocked: false },
  { id: 'se-306', subjectId: 's-11', teacherId: 't-7', roomId: 'r-103', divisionId: 'div-7a', day: 'Thursday', period: 1, span: 1, isLocked: false },
];
